***Introduction***

In [ ]:
# 1-D arrary
import numpy as np
s1=np.array([1,2,3,4])

#2-D    (matrix)
s2=np.array([[1,2,3],[4,5,6]])

#multi dimensional 
s3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s3)

a=[50,60,70,80,90,100]
import numpy as np
arr=np.array(a)
print(arr)

print(arr.shape)
print(arr.mean())
print(arr.dtype)
print(arr.max())

In [ ]:
#Creating array
import numpy as np
s1=np.array([1,2,3,4,5])

#with default values
zeroes_Array=np.zeros((3,3))         #np.zeroes(3)
print(zeroes_Array)

one_Array=np.ones((3,3))                
print(one_Array)

filld_Array=np.full((3,3),25)
print(filld_Array)

In [2]:
'''
creating sequence of numbers in numpy
arange()
arnge(start,stop,step)
'''
import numpy as np
arr=np.arange(1,28,1)
print(arr)

'''
Creating identity matrix
eye(size)
'''
identity_matrix=np.eye(4)
print(identity_matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


***Array properties and operations***

In [3]:
'''Find shape of array'''
import numpy as np
# arr_2d=np.array([[1,2,3],[4,5,6]])
# print(arr_2d.shape)                     #(2, 3) 2-rows, 3-column


'''Find size of array'''
# arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# print(arr.size)                         #10 numbers are there


'''Check how many dimensions are'''
# arr_1=np.array([145,6,345,56])
# arr_2=np.array([[757,8,65,63],[75,86,9689,86]])
# arr_3=np.array([[[1,2,3,4],[3,56,7,26],[75,3,5,75]]])
# print(arr_1.ndim)
# print(arr_2.ndim)
# print(arr_3.ndim)


'''What type of data store'''
# arr_5=np.array([10,20,30])
# print(arr.dtype)                    #int64


'''conversion'''
# arr_6=np.array([2.3,47.65])
# print(arr_6)
# cnvrt=arr_6.astype(int)
# print(cnvrt)
# print(cnvrt.dtype)

arr_7=np.array([1,2,3,4,5,])
arr_8=arr_7.astype(float)
print(arr_8)

[1. 2. 3. 4. 5.]


***Maths Operations***

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])

# print(arr+5)
# print(arr-29)
# print(arr*6)
# print(arr/2)
# print(arr**2)

'''Aggresion function (unoversal funtion)'''
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))          #standard deviaton
print(np.var(arr))          #varision


Summary:-
.shape , .size , .dtype , .astype , +-*/ , 

***indexing and Slicing***

In [ ]:
''''indexing'''

import numpy as np
# arr_1=np.array([10,20,30,40,50])
# print(arr_1[0])
# print(arr_1[-1])


'''Slicing'''
# arr_2=np.array([110,120,130,140,150])
# print(arr_2[2:4])
# print(arr_2[:4])
# print(arr_2[::2])
# print(arr_2[::-1])


'''fancy indexing'''
# arr_3=np.array([10,20,30,40,50])
# print(arr_3[[1,2,4]])                   #Give elements at index 1,2,4


'''Filtering'''
arr_4=np.array([50,60,70,80,90,100])
print(arr_4[arr_4>60])
import matplotlib.pyplot as plt



[ 70  80  90 100]


***Reshaping and Manupulating array***

In [ ]:
'''reshape(rows,columns)'''

# import numpy as np
# arr = np.array([1,2,3,4,5,6])
# reshaped_array=arr.reshape(2,3)
# print(reshaped_array)


'''
.ravel() ->view
.flatten ->copy
'''

arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2.ravel())
print(arr_2.flatten())

indexing
slicing
facncy indexing
boolean masking
array reshape
ravel ,flatten

***Reshaping and Manipulating Arrays (Advance Numpy)***

In [ ]:
'''
#Note-> Whenever we perform operations like insert , append we have to crate new array
np.insert(array , index , value , asix=None)
array - Original array
index - 
value - 
axis -
axis -0 , row-wise
axis -1 , column wise
'''
'''Using append'''
import numpy as np
# arr_app=np.array([10,20,30,40,50])
# new_app=np.append(arr_app , [60,70,80,90,100])
# print(new_app)


'''insert number in 1-D array '''
import numpy as np
# arr = np.array([10,20,30,40,50])
# print(arr)
# new_arr = np.insert(arr, 5,2528)
# print(new_arr)


'''insert elements at multi-D Array'''
# arr_add=np.array([[1,2],[3,4],[5,6]])
# new_1=np.insert(arr_add , 1,[7,8], axis=0)
# new_2=np.insert(arr_add , 1,[7,8], axis=None)
# print(new_1)
# print(new_2)

'''np.concatenate((arr1,arr1),axis=0)'''
arr_c1=np.array([1,2,3,4,5])
arr_c2=np.array([6,7,8,9,10])
arr_c_new=np.concatenate((arr_c1,arr_c2))
print(arr_c_new)

In [ ]:
'''Delete elements
np.delete(array , index , ais=None)
'''

import numpy as np
# d1=np.array([10,20,30,40,50])
# new_d=np.delete(d1,3)
# print(new_d)

d2=np.array([[1,2,3],[4,5,6]])
new_d3=np.delete(d2,0,axis=0)
print(new_d3)

In [ ]:
'''stacking
vstack() row wise
hstack() column wise
'''
import numpy as np
# arr1=np.array([1,2,3])
# arr2=np.array([4,5,6])
# print(np.vstack((arr1,arr2)))
# print(np.hstack((arr1,arr2)))

'''
np.split() -> equal

np.vsplit()
np.hsplit()
'''
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,2))


***Broadcasting & Vectorization***

In [ ]:
'''We can perform mathematical operations easily'''
# prices=[100,200,300,400]
# new=[]
# discount=10
# for i in prices:
#     new_price=i-(i*discount/100)
#     new.append(new_price)
# print(new)

'''this is much easier   '''
prices=np.array([[100,200,300,400]])
discount=10
final=prices-(prices*discount/100)
print(final)

In [ ]:
# import numpy as np
# arr1=np.array([10,20,30,40,50])
# print(arr1+10)

# arr2=np.array([[1,2,3],[4,5,6]])
# vector=np.array([1,2,3])
# print(arr2+vector)

'''error'''
# arr3=np.array([[1,2,3],[4,5,6]])
# arr4=np.array([1,2])                    #ValueError  
# print(arr3+arr4)               


'''Vectorization'''
import numpy as np
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1+v2)                #[5 7 9]

print(v1*v2)                #[ 4 10 18]

***Handling Missing Values***


In [ ]:
''' np.nan ->detect missing values'''   #nan-not a number

import numpy as np

# arr=np.array([1,2,np.nan,4,5,np.nan])       #[False False  True False False  True]
# print(np.isnan(arr))

# new=np.nan_to_num(arr,nan=28)
# print(new)                                  #[ 1.  2. 28.  4.  5. 28.]

''' np.isinf(arr)'''


arr1=np.array([1,2,np.inf,4,5,6,7,-np.inf])
print(np.isinf(arr1))                           #[False False  True False False False False  True]

new2=np.nan_to_num(arr1,posinf=1000,neginf=-100)
print(new2)                                     #[   1.    2. 1000.    4.    5.    6.    7. -100.]